modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="more_damage_items"
version="1.0.0"
displayName="More damage items"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="scwin, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.more_damage_items]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration